### ISSUE TITLE
mixer.h is missing "USB_MIXER_BESPOKEN"

### ISSUE THREAD

**Issue by FluxTape** [Focusrite-Scarlett-on-Linux/sound-usb-kernel-module#10]
`mixer.h` needs to be updated to include `USB_MIXER_BESPOKEN,` in the enum on line 58, otherwise it won't build

**Comment by HinTak** [comment]
Aoplogies - fixed in https://github.com/Focusrite-Scarlett-on-Linux/sound-usb-kernel-module/commit/30b6e6512e3319a93b5f0582ed02b4bd959389d2 . But that's the older branch - you should switch to v5.12-sound-master branch (which is also the new default).
