### ISSUE TITLE
Pipewire - suspended -> error (Start error: Invalid argument)

### ISSUE THREAD

**Issue by mikefaille** [Focusrite-Scarlett-on-Linux/sound-usb-kernel-module#13]
When I use pipewire and I try to connect directly 2 interface, I have this error : 

```
ct 02 17:52:51 pop-os pipewire[19565]: spa.alsa: Broken configuration: no configurations available: Invalid argument
Oct 02 17:52:51 pop-os pipewire[19565]: spa.alsa: Broken configuration: no configurations available: Invalid argument
Oct 02 17:52:51 pop-os pipewire[19565]: spa.alsa: Broken configuration for playback: no configurations available: Invalid argument
Oct 02 17:52:51 pop-os pipewire[19565]: pw.node: (alsa_input.usb-Focusrite_Scarlett_18i8_USB_F96G6XP1283E26-00.pro-input-0-69) suspended -> error (Start error: Invalid argument)
Oct 02 17:52:54 pop-os pipewire[19565]: spa.alsa: Broken configuration: no configurations available: Invalid argument
Oct 02 17:52:54 pop-os pipewire[19565]: spa.alsa: Broken configuration: no configurations available: Invalid argument
Oct 02 17:52:54 pop-os pipewire[19565]: spa.alsa: Broken configuration for playback: no configurations available: Invalid argument
Oct 02 17:52:54 pop-os pipewire[19565]: pw.node: (alsa_input.usb-Focusrite_Scarlett_18i8_USB_F96G6XP1283E26-00.pro-input-0-69) suspended -> error (Start error: Invalid argument)
Oct 02 17:52:57 pop-os pipewire[19565]: spa.alsa: Broken configuration: no configurations available: Invalid argument
Oct 02 17:52:57 pop-os pipewire[19565]: spa.alsa: Broken configuration: no configurations available: Invalid argument
Oct 02 17:52:57 pop-os pipewire[19565]: spa.alsa: Broken configuration for playback: no configurations available: Invalid argument
Oct 02 17:52:57 pop-os pipewire[19565]: pw.node: (alsa_input.usb-Focusrite_Scarlett_18i8_USB_F96G6XP1283E26-00.pro-input-0-69) suspended -> error (Start error: Invalid argument)

```

Can it be an issue at driver side ?
I documented the error on Pipewire side too : https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1995

**Comment by mikefaille** [comment]
It looks like related to this issue too : https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1995

@geoffreybennett According the Pipewire main dev this error is unknown from him and come from Alsa : https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1948#note_1227101

**Comment by mikefaille** [comment]
cc:  @sadko4u

**Comment by geoffreybennett** [comment]
Hi Mike, if you disable the mixer driver (remove the module device_setup option or set to 0, then confirm dmesg says "Focusrite Scarlett Gen 2/3 Mixer Driver disabled") does that fix the problem?

**Comment by mikefaille** [comment]
I have the same issue (with full details from pipewire logs, dmesg lines and no monitor on pavucontrol ) : 
![Screenshot from 2022-01-31 17-29-22](https://user-images.githubusercontent.com/978196/151899969-d33ede1e-989a-4fee-b194-ba789b7c8c00.png)

Here is my pw-dump result : 
[pipewire-setup0.log](https://github.com/Focusrite-Scarlett-on-Linux/sound-usb-kernel-module/files/7975286/pipewire-setup0.log)

**Comment by geoffreybennett** [comment]
That's a pipewire or alsa problem then, unrelated to the mixer driver. Next step: does going back to kernel 5.10 fix the problem?

**Comment by mikefaille** [comment]
@geoffreybennett It does work with the kernel 5.10.

Here is my test to reproduce it :

1. getting the kernel 5.10 from https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.10/
2. starting on `recovery mode` (as my Nvidia module doesn't compile)
3. `systemctl isolate multi-user` 
4. login with my user to bring the same pipewire config.
5. using `pulsemixer` to make sure my Scarlet focusrite 18i8 is the default input and I use the `pro mode`
6. using `parecord out.wav` to record my audio
7. my audio file is actually working. 

If I use the kernel 5.15 with the steps 5. to 7. the audio file is empty.

Here is my `pw-dump` for the kernel 5.10 : [pw-dump5.10.log](https://github.com/Focusrite-Scarlett-on-Linux/sound-usb-kernel-module/files/8007688/pw-dump5.10.log)

^ this dump may contain the pulseaudio profile configuration.

**Comment by mikefaille** [comment]
@geoffreybennett I don't know if you saw my answer or if it's appropriate on opensource project to ping someone as you are free to help; I'm sorry if it's not the case. I just wanted to know if you saw my answer. I'm ready to help at your desire.

**Comment by geoffreybennett** [comment]
Hi Mike, thanks for the ping. As the problem seems unrelated to the mixer driver, and only dependent on the kernel version, that would indicate to me that it's a problem with the ALSA driver. I would suggest subscribing to the alsa-devel mailing list at https://alsa-project.org/wiki/Mailing-lists and asking on there. I see that Tobias Guggenmos here: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1948#note_1240242 tried narrowing down the issue with a git bisect but failed. If you could do a git bisect and identify the broken commit, that would be very helpful in finding/fixing the issue.

**Comment by mikefaille** [comment]
I just created a ticket on the Kernel bug tracker : https://bugzilla.kernel.org/show_bug.cgi?id=215792

I just subscribe to the Alsa-dev mailing list wishing some feedback.

For the kernel dissect, I would as soon I have time ! At least, my focus is trying to make sure this issue is well documented.

**Comment by mikefaille** [comment]
@geoffreybennett Thank you ! It seems we found the issue ! A Linux patch is incoming !
https://bugzilla.kernel.org/show_bug.cgi?id=215792#c33

**Comment by geoffreybennett** [comment]
Thanks for pointing that out! This patch also fixed the same issue I was having with my Qu-16.
