### ISSUE TITLE
Clarett 8pre USB Kernel ?

### ISSUE THREAD

**Issue by juanpc2018** [Focusrite-Scarlett-on-Linux/sound-usb-kernel-module#18]
https://github.com/opensrc/alsa/issues/48

https://github.com/geoffreybennett/alsa-scarlett-gui/issues/30

https://github.com/geoffreybennett/alsa-scarlett-gui/issues/28

**Comment by HinTak** [comment]
@geoffreybennett explained a few times already: while Scarlett may offer the same user interface for the same software for two different devices, ultimately they are different devices. One is supported at the driver level by current linux kernel code, the other is not, and also not planned in the recent future.
Let's see if @sadko4u is interested in write new driver code for another and different hardware. For the time being I assume the answer is no, not in the recent future.

**Comment by geoffreybennett** [comment]
There is a Clarett+ 8Pre USB Linux driver in the works, coming soon.

**Comment by geoffreybennett** [comment]
Clarett+ 8Pre support is available from here now: https://github.com/geoffreybennett/scarlett-gen2/commits/scarlett-gen3

**Comment by HinTak** [comment]
I 'll put that out as a clarett-8pre branch on the dkms module. Thanks.
