### ISSUE TITLE
Add support for Scarlett 4th Gen

### ISSUE THREAD

**Issue by alisonkit** [Focusrite-Scarlett-on-Linux/sound-usb-kernel-module#20]
The new gen came out and I'm sure other people will start to purchase them more as Gen 3 is phased out, as it seems to be a popular audio interface for Linux. Personally I am looking forward to get a 4th Gen Solo.

If needed I could also try and help out with enabling functionality if I end up purchasing one, in any case that it doesn't work out of the box.

I've been reading the [user guide](https://fael-downloads-prod.focusrite.com/customer/prod/downloads/scarlett_solo_4th_gen_user_guide-pdf-en.pdf) and it seems like it's very similar to the 3rd gen when it comes to deactivating MSD (or as they call, Easy Start). There also seems to be [official support for ChromeOS](https://support.focusrite.com/hc/en-gb/articles/12820556548882-ChromeOS-Support), compared to the 3rd Gen where it says no official support.

I also wonder if the last parameter (`options snd_usb_audio device_setup=1,1,1,1`) is something that could work with the 4th gen.

Thank you.

**Comment by sadko4u** [comment]
Maybe @geoffreybennett can help you here.
I'm under sanctions now and stopped any development until the peace comes to our doors again.

**Comment by sadko4u** [comment]
As I see at this moment, the gen 4 looks like the renewal of minor Scarlett models. I don't see 8i20 and 18i20 gen4 on the Focusrite site at this moment. That probably can mean that just adding corresponding device IDs to the driver can be enough.

**Comment by sadko4u** [comment]
For me the fundrasing link doesn't work. Maybe because I'm visiting the site from Russia.

**Comment by geoffreybennett** [comment]
> As I see at this moment, the gen 4 looks like the renewal of minor Scarlett models. I don't see 8i20 and 18i20 gen4 on the Focusrite site at this moment. That probably can mean that just adding corresponding device IDs to the driver can be enough.

There's definitely new features. I see at least:
- The gain control is digitally controlled
- Auto-gain & "Safe" settings
- Input levels are sent over USB (previous gens only send mux output levels)
- Air mode has an extra option

**Comment by alisonkit** [comment]
> > As I see at this moment, the gen 4 looks like the renewal of minor Scarlett models. I don't see 8i20 and 18i20 gen4 on the Focusrite site at this moment. That probably can mean that just adding corresponding device IDs to the driver can be enough.
> 
> There's definitely new features. I see at least these things which are relevant to the driver:
> 
>     * The gain control is digitally controlled
> 
>     * Auto-gain & "Safe" settings
> 
>     * Input levels are sent over USB (previous gens only send mux output levels)
> 
>     * Air mode has an extra option

**Comment by alisonkit** [comment]
@geoffreybennett Thank you for updating on the situation. Hope you can get the devices!

And @sadko4u I'm really sorry to hear about your situation, I hope you're able to peacefully get out of it.

Let's see how this develops... Thank you all for your help so far.

Alison

**Comment by geoffreybennett** [comment]
First draft of Scarlett Gen 4 support is ready for the brave:
Kernel driver: https://github.com/geoffreybennett/scarlett-gen2/releases/tag/v6.5.11-g4.1
Firmware update utility: https://github.com/geoffreybennett/scarlett2
Please email me if you'd like to help test.

FYI, the protocol is the same as Gen2/3/Clarett, but the types of controls are very different and there were a lot of changes:
```
[g@fedora linux]$ git show upstream:sound/usb/mixer_scarlett2.c | wc -l
4549
[g@fedora linux]$ git show scarlett-gen4:sound/usb/mixer_scarlett2.c | wc -l
7131
```
