### ISSUE TITLE
Nothing happens after depmod -a

### ISSUE THREAD

**Issue by mycroftsnm** [Focusrite-Scarlett-on-Linux/sound-usb-kernel-module#9]
Hi, im trying to install this driver, followed all steps, copied  the 2 .ko in /lib/modules/`uname -r`/updates  but i dont get any message after _depmod -a_ . Im sure im doing something wrong but idk what.  About the certs part, i dont really know if my kernel has CONFIG_MMODULE_SIG_FORCE=y , probably yes. but i don't know how to create the certs , this is pretty advanced to me, so i will be grateful if u can help me. My distro is Arch and i have a scarlett 18i8 gen3.

**Comment by HinTak** [comment]
On next reboot, with `dmesg`:
"You should see Focusrite Scarlett Gen 2/3 Mixer Driver enabled [sadko4u mod] ... for one, and Focusrite Scarlett Gen 2/3 Mixer Driver enabled v5.12.9s1 ... for the other."

`depmod -v -a` shows verbose changes, which should show the update directory being scanned. It is not very useful and perhaps even confusing.

**Comment by mycroftsnm** [comment]
dmesg says: usb 1-6: Focusrite Scarlett Gen 2/3 Mixer Driver disabled; use options snd_usb_audio vid=0x1235 pid=0x8210 device_setup=1 to enable and report any issues to g@b4.vu
How can i set that options?

**Comment by HinTak** [comment]
See https://github.com/geoffreybennett/scarlett-gen2/releases ; I 'll add that instruction to the readme at some stage. They will become the default at some time in the future.

**Comment by mycroftsnm** [comment]
Thank u very much , its working nice :) .

**Comment by HinTak** [comment]
I have duplicated the instruction to the readme now. Thanks for the feedback.
